### ISSUE TITLE
Why No Minimum Heat Index Pop-up - Main Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OSHA-Heat-Safety-iOS#10]
There is no longer a pop-up informing me that there ares no heat index issues if the temperature is under 80F, like in the old application.

**Comment by skeeJay** [comment]
The alert was evocative of an error message and made users believe they had done something wrong. We replaced it with the new gray/neutral "Minimal Risk From Heat" state.

**Comment by jfc3-dol** [comment]
Okay, we wanted to make sure an old feature wasn't being removed when it was still required.

Closing issue.
