### ISSUE TITLE
Why No Easy Way Out of Numbers Keyboard - Main Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OSHA-Heat-Safety-iOS#12]
There seems to be no way to get back to the main screen without tapping on the "Set" button, which I think might make more sense to be either "Done" or "Calculate".

**Comment by skeeJay** [comment]
Unfortunately, the iOS numeric keypad does not contain a return key, as the alphabetic keypad does, necessitating the addition of the toolbar with a completion button. I'm not married to "Set," but I foresaw problems with "Done" and "Calculate." "Done" usually implies that a modal will be closed, but in this case the keypad will not only be closed but will change the state of the app with the entered value; thus, I wanted something different. On the other hand, "Calculate" was a longer, more descriptive, possibly distracting term that didn't have the succinctness of the usual completion terms like "Done" or "OK." Hence "Set." I'm not married to it, but that was the reasoning.

**Comment by MikePulsiferDOL** [comment]
Personally, I do like "Calculate" better as at first, I didn't even see the word "Set."  It's also action-oriented, which makes it infinitely better than "OK" or "Done."

**Comment by skeeJay** [comment]
I'm cool with "Calculate." I'll make the change.

**Comment by jfc3-dol** [comment]
Calculate works great for me and when testing with VoiceOver.

I'm going to close this issue.
