### ISSUE TITLE
Additional Words Spoken by VoiceOver Which are Not on Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OSHA-Heat-Safety-iOS#18]
While testing the last set of updates when VoiceOver read the following text "Feels like 115 F" it spoke "Feels like 115 masculine ordinal F".

Not sure if this is because it has to do with an issue with the Spanish version of the application that we are testing later.

If you want to come down and listen to this send me an e-mail.

**Comment by MikePulsiferDOL** [comment]
They are two different characters: º°

One is a degree symbol: Shift-Option-8 on the Mac keyboard
The other is the masculine ordinal: Option-0 on the Mac keyboard

http://en.wikipedia.org/wiki/Ordinal_indicator

**Comment by skeeJay** [comment]
Can correct this afternoon.

**Comment by jfc3-dol** [comment]
VoiceOver read the text correctly as "Feels like 115 degrees Fahrenheit".

Closing issue.
