### ISSUE TITLE
Spanish Pages in English Dialect on Information Pages 

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OSHA-Heat-Safety-iOS#19]
While using VoiceOver  with the Language set to Spanish in the information pages we found the first three pages where written in Spanish but pronounced with an English dialect.

The pages in question are:
- Senales y Sintomas
- Primeros Auxillos
- Mas Detalles

**Comment by MikePulsiferDOL** [comment]
what do you mean by "English dialect?" Was it speaking in English or Spanish?

**Comment by jfc3-dol** [comment]
VoiceOver spoke Spanish as an English accented person. So it was like me speaking Spanish without knowing the correct  pronunciation or accent on words. The other pages were fine.

My guess is the language for the pages were still set at English and not Spanish, since I think these are HTML pages.

lang="en" instead of lang="es"

**Comment by MikePulsiferDOL** [comment]
Minor issue.  Can be fixed in the next release.

**Comment by jfc3-dol** [comment]
If the pages are HTML as I think they are, since E J said they had ALT text. Tey should easily be able to switch languages from:

lang="en" to lang="es"

**Comment by skeeJay** [comment]
Can correct this afternoon.

**Comment by jfc3-dol** [comment]
VoiceOver read text with a Spanish accent like the rest of the pages.

Closing issue.
