### ISSUE TITLE
Links Going to OSHA Website Were in English When Coming form Spanish Pages

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OSHA-Heat-Safety-iOS#20]
When having the Heat Index application change to Spanish we found an link that went to the website was sent to one in English not Spanish.

**Comment by MikePulsiferDOL** [comment]
Does one exist in Spanish?

**Comment by jfc3-dol** [comment]
I do not know. 

Would assume there should be and the links should go to them. If not I assume they should create Spanish version of the web pages.

**Comment by MikePulsiferDOL** [comment]
Pre-existing issue.

I believe this should wait until the next release.  If no Spanish-language content exists, then this issue should be closed.

**Comment by MikePulsiferDOL** [comment]
Spanish version does exist: https://www.osha.gov/SLTC/heatillness/spanish/index_sp.html

**Comment by skeeJay** [comment]
Can correct this afternoon.

**Comment by jfc3-dol** [comment]
Links sent person to Spanish version of the OSHA website page as expected.

Closing issue.
