### ISSUE TITLE
Internal Link and Back Button Usabliity Issue

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OSHA-Heat-Safety-iOS#22]
When a person clicks/taps an internal link in the Heat Index they go to another page. When they use the link/back button at top of page it takes the to the main application page/screen and not the previous page/screen.

This might be something we fix In the next version to make it easier to use.

**Comment by MikePulsiferDOL** [comment]
It's consistent with UI conventions in iOS.
