### ISSUE TITLE
Poor Color Contrast - Information Section

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OSHA-Heat-Safety-iOS#5]
When coming from the main page to see the additional information section all the button/link text is the color of the heat index, which makes it difficult to read on the gray background.

WCAG 2.0 - 1.4.3 - Contrast (Minimum) - Level AA

**Comment by skeeJay** [comment]
This was simply a little design flourish, but the colors chosen are actually darker versions of heat color to maximize readability. For example, the yellow is the same as the yellow used in Apple's Notes app.

**Comment by jfc3-dol** [comment]
Let me look into what text color combinations will work with the background colors and get back to you.

One of a hand full of tools that I use to check color contrast are the following links, which tell you if you passed WCAG 2.0 AA or not. DOL is moving towards WACG 2.0 AA because the Section 508 fresh will be using them in the future. 

The color contrast ratio needs to be 4.5:1 or higher, Where ours currently are between 1.5:1 and 2.8:1 or something like that.

http://snook.ca/technical/colour_contrast/colour.htm - Snook Color Contrast were you enter text and background color, which tells you if you passed or not.

http://www.paciellogroup.com/resources/contrastanalyser/ - Paciello Group color contrast application that you can download. This uses an eye dropper to find the colors you want to check.

There are more if you need them
