### ISSUE TITLE
Larger Text - Information Section and Heat Risk Screens

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OSHA-Heat-Safety-iOS#7]
The text needs to be large for people with poor eyesight or other visual issues. Most elderly people are likely going to need larger text to see the information you are providing.

WCAG 2.0 - 1.4.4 - Resize Text - Level AA

**Comment by skeeJay** [comment]
The text is actually actually the same size and in the cases of headers, larger, than the text in these screens in the current app, so this is not a regression. But I'm curious what the recommended point size for body text would be.

**Comment by jfc3-dol** [comment]
Let me look at this more so i can give you better advice.

**Comment by skeeJay** [comment]
Thanks, @jfc3-dol, I'm interested to hear what the standard is. I don't have any problem making the body text larger......in any case, it's already larger than the tiny body text in the current app, so it's hopefully an improvement.

**Comment by jfc3-dol** [comment]
Thanks, closing this issues, since the text is easier to read because it larger and better color contrast.
