### ISSUE TITLE
Underline Not Need - Information Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OSHA-Heat-Safety-iOS#9]
Why under the "More Details" in the "More Info" part of the application is there text that is underlined which are not links. Having underlines in the text makes me think it's a link to more content.

**Comment by skeeJay** [comment]
This is copy taken from the current app, so not a regression. I can remove the underlines, but I'd be changing OSHA's approved copy.

**Comment by jfc3-dol** [comment]
Can we see if we can remove the unnecessary underlines, since at least two or three of us over here OPA DEC QA/Accessibility assumed they were links.

**Comment by skeeJay** [comment]
Yes, I can take care of. Don't think anyone at OSHA will mind.

**Comment by skeeJay** [comment]
Forgot to mention it in the commit, but this is covered by f0190d419a9adfd9786614ed3374429622cd5c1e

**Comment by jfc3-dol** [comment]
Thanks, for removing the underlines.

Closing issue.
